In [15]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [16]:
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Q1 Read the input file and check the data dimension


In [4]:
#Read input file and understand the data
# "default" is my dependent variable



In [5]:
german = pd.read_csv("german_credit.csv")

german.head(5)



default account_check_status  duration_in_month  \
0        0               < 0 DM                  6   
1        1    0 <= ... < 200 DM                 48   
2        0  no checking account                 12   
3        0               < 0 DM                 42   
4        1               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex  ... present_res_since  \
0                        male : single  ...                 4   
1  female : divorced/separated/married  ...                 2   
2                        male : single  ...                 3   
3                        male : single  ...                 4   
4                        male : single  ...                 4   

                                            property age  \
0                                        real estate  67   
1                                        real estate  22   
2                                        real estate  49   
3  if not A121 : building society savings agreeme...  45   
4                              unknown / no property  53   

   other_installment_plans   housing credits_this_bank  \
0                     none       own                 2   
1                     none       own                 1   
2                     none       own                 1   
3                     none  for free                 1   
4                     none  for free                 2   

                           job people_under_maintenance  \
0  skilled employee / official                        1   
1  skilled employee / official                        1   
2         unskilled - resident                        2   
3  skilled employee / official                        2   
4  skilled employee / official                        2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes  

[5 rows x 21 columns]

In [6]:
german.shape


(1000, 21)

In [7]:
print(german.dtypes)


default                        int64
account_check_status          object
duration_in_month              int64
credit_history                object
purpose                       object
credit_amount                  int64
savings                       object
present_emp_since             object
installment_as_income_perc     int64
personal_status_sex           object
other_debtors                 object
present_res_since              int64
property                      object
age                            int64
other_installment_plans       object
housing                       object
credits_this_bank              int64
job                           object
people_under_maintenance       int64
telephone                     object
foreign_worker                object
dtype: object


In [128]:
# Lets build a Ensemble model but need to modify the dataset first


### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [8]:
# Print Shape of model data


In [9]:
german_df = pd.get_dummies(german, columns = ['account_check_status', 'credit_history', 'purpose','savings','present_emp_since','personal_status_sex','other_debtors','property','other_installment_plans','housing','job','telephone','foreign_worker'])


In [10]:
german_df.head()


default  duration_in_month  credit_amount  installment_as_income_perc  \
0        0                  6           1169                           4   
1        1                 48           5951                           2   
2        0                 12           2096                           2   
3        0                 42           7882                           2   
4        1                 24           4870                           3   

   present_res_since  age  credits_this_bank  people_under_maintenance  \
0                  4   67                  2                         1   
1                  2   22                  1                         1   
2                  3   49                  1                         2   
3                  4   45                  1                         2   
4                  4   53                  2                         2   

   account_check_status_0 <= ... < 200 DM  account_check_status_< 0 DM  ...  \
0                                       0                            1  ...   
1                                       1                            0  ...   
2                                       0                            0  ...   
3                                       0                            1  ...   
4                                       0                            1  ...   

   housing_own  housing_rent  \
0            1             0   
1            1             0   
2            1             0   
3            0             0   
4            0             0   

   job_management/ self-employed/ highly qualified employee/ officer  \
0                                                  0                   
1                                                  0                   
2                                                  0                   
3                                                  0                   
4                                                  0                   

   job_skilled employee / official  job_unemployed/ unskilled - non-resident  \
0                                1                                         0   
1                                1                                         0   
2                                0                                         0   
3                                1                                         0   
4                                1                                         0   

   job_unskilled - resident  telephone_none  \
0                         0               0   
1                         0               1   
2                         1               1   
3                         0               1   
4                         0               1   

   telephone_yes, registered under the customers name   foreign_worker_no  \
0                                                  1                    0   
1                                                  0                    0   
2                                                  0                    0   
3                                                  0                    0   
4                                                  0                    0   

   foreign_worker_yes  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  

[5 rows x 62 columns]

In [11]:
german_df.shape



(1000, 62)

### Check for highly correlated variables but don't required any treatment for this use case

In [13]:
np.cov(german_df)


array([[ 22053.85404548, 112051.69962983,  39494.0433633 , ...,
         15157.85616076,  34739.45425701,  86165.61660497],
       [112051.69962983, 570960.74167107, 201028.77895293, ...,
         77058.88656795, 176943.53225806, 439008.67689053],
       [ 39494.0433633 , 201028.77895293,  70807.88471708, ...,
         27154.30883131,  62307.70597567, 154575.97408778],
       ...,
       [ 15157.85616076,  77058.88656795,  27154.30883131, ...,
         10420.42120571,  23892.40692755,  59256.55896351],
       [ 34739.45425701, 176943.53225806,  62307.70597567, ...,
         23892.40692755,  54854.28476996, 136057.39608673],
       [ 86165.61660497, 439008.67689053, 154575.97408778, ...,
         59256.55896351, 136057.39608673, 337554.32046536]])

In [17]:
corr_matrix = german_df.corr().abs()
print(corr_matrix)

                                                     default  \
default                                             1.000000   
duration_in_month                                   0.214927   
credit_amount                                       0.154739   
installment_as_income_perc                          0.072404   
present_res_since                                   0.002967   
...                                                      ...   
job_unskilled - resident                            0.021822   
telephone_none                                      0.036466   
telephone_yes, registered under the customers n...  0.036466   
foreign_worker_no                                   0.082079   
foreign_worker_yes                                  0.082079   

                                                    duration_in_month  \
default                                                      0.214927   
duration_in_month                                            1.000000   
credit_amoun

### Drop the original variables which are converted to dummy

In [ ]:
# Dropped the Original values in above pd.get_dummies 


### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [34]:
# split the Features and Target values.
# X contains various features
# Y contains the target column
array = german_df.values
X = array[:,1:63]  
Y = array[:,0]
print(X)
print(Y)


[[   6 1169    4 ...    1    0    1]
 [  48 5951    2 ...    0    0    1]
 [  12 2096    2 ...    0    0    1]
 ...
 [  12  804    4 ...    0    0    1]
 [  45 1845    4 ...    1    0    1]
 [  45 4576    3 ...    0    0    1]]
[0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0
 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 1 0 1
 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1
 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1
 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0
 0 0 0 0 1 1 0 0 1 0 0

In [35]:
print(X.shape)
print(Y.shape)

(1000, 61)
(1000,)


In [38]:
from sklearn.model_selection import train_test_split
test_size = 0.30 

seed = 7  # Random number seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(700, 61)
(300, 61)
(700,)
(300,)


### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999



In [39]:
from sklearn.ensemble import RandomForestClassifier
rfcl = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)
rfcl = rfcl.fit(X_train, y_train)




### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [42]:
#Accuracy
rfcl.score(X_test , y_test)


0.8

### Q6 Show the list of the features importance( 1 Marks)

In [44]:
#confusion matrix
from sklearn import metrics

y_predict = rfcl.predict(X_test)
print(metrics.confusion_matrix(y_test, y_predict))



[[204  13]
 [ 47  36]]


### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [49]:
from sklearn import model_selection
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score


In [50]:
# Use below values
num_folds = 10
seed = 77


In [51]:
#Validate the Random Forest model build above using k fold


In [58]:
'''
scoring = 'accuracy'
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(RandomForestClassifier, X, Y, cv=kfold, scoring=scoring)
'''

seed = 77

kfold = model_selection.KFold(n_splits=10, random_state=seed)
print (kfold)
model = RandomForestClassifier(n_estimators=10, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
model.fit(X, Y)

print(model.score(X, Y))


KFold(n_splits=10, random_state=77, shuffle=False)
0.982


In [0]:
#Calculate Mean score


In [59]:
print(results.mean())


0.7530000000000001


In [0]:
# Calculate score standard deviation using std()


In [60]:
print(results.std())


0.029000000000000022


# Q8 Print the confusion matrix( 1 Marks)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
(2 Marks)

[link text](https://)### Bootstrapping ( Bonus and Optional)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [0]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []


In [0]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfm.fit(X_, y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)
    

In [0]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())


Accuracy Score
Avearge:  0.6893333333333334
Standard deviation:  0.014966629547095768
