# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x


TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42) # For 2.x


## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
irisdata = load_iris()


In [6]:
irisdata

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [37]:
irisdata.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
irisdata.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = irisdata.data

In [0]:
y = irisdata.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [11]:
X_train.shape

(112, 4)

In [12]:
X_test.shape

(38, 4)

## Question 4

In [13]:
from keras.utils import to_categorical
y_test=to_categorical(y_test, num_classes = 3)
y_train=to_categorical(y_train, num_classes = 3)

Using TensorFlow backend.


### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow import keras

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from keras.models import Sequential
from tensorflow.keras.layers import Dense


In [0]:
from tensorflow.keras import layers
model = tf.keras.Sequential()



## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Input layer
model.add(Dense(4, activation='sigmoid', input_shape=(4,)))

# Output layer
model.add(Dense(3, activation='softmax'))




## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [21]:
model.fit(X_train,y_train,batch_size=1,nb_epoch=10,verbose=1,validation_data=(X_test,y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/10
112/112 [==============================] - 1s 7ms/sample - loss: 1.1255 - accuracy: 0.4464 - val_loss: 1.0498 - val_accuracy: 0.7105
Epoch 2/10
112/112 [==============================] - 0s 2ms/sample - loss: 1.0544 - accuracy: 0.6339 - val_loss: 1.0031 - val_accuracy: 0.7105
Epoch 3/10
112/112 [==============================] - 0s 2ms/sample - loss: 1.0091 - accuracy: 0.6518 - val_loss: 0.9671 - val_accuracy: 0.7368
Epoch 4/10
112/112 [==============================] - 0s 2ms/sample - loss: 0.9734 - accuracy: 0.6964 - val_loss: 0.9290 - val_accuracy: 0.7368
Epoch 5/10
112/112 [==============================] - 0s 2ms/sample - loss: 0.9375 - accuracy: 0.7232 - val_loss: 0.8966 - val_accuracy: 0.7105
Epoch 6/10
112/112 [==============================] - 0s 2ms/sample - loss: 0.9046 - accuracy: 0.6607 - val_loss: 0.8580 - val_accuracy: 0.7368
Epoch 7/10
112/112 [==============================] - 0s 2ms/sample - loss: 0.8708 - accura

## Question 10

### Make predictions
- Predict labels on one row

In [22]:
# score
score=model.evaluate(X_test,y_test)

38/38 [==============================] - 0s 2ms/sample - loss: 0.7259 - accuracy: 0.8158


In [23]:
score

[0.7258632402671011, 0.81578946]

In [0]:
y_predict = model.predict(X_test)

In [25]:
y_predict[0]

array([0.20462401, 0.38269827, 0.4126777 ], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [27]:
y_pred = np.round(model.predict(X_test))
y_pred[0:1]

array([[0., 0., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [30]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [35]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [36]:
import io
import pandas as pd
import numpy as np
shares = pd.read_csv('prices.csv')
shares.head()


date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [86]:
shares_ori = shares.copy()
shares_ori.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [37]:
shares.drop(['date', 'symbol'], axis = 1, inplace = True) 
shares.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [38]:
shares.tail(5)

open       close         low        high     volume
851259  103.309998  103.199997  102.849998  103.930000   973800.0
851260   43.070000   43.040001   42.689999   43.310001  1938100.0
851261   53.639999   53.529999   53.270000   53.740002  1701200.0
851262   44.730000   45.450001   44.410000   45.590000  1380900.0
851263   54.200001   53.630001   53.389999   54.480000   705100.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [39]:
shares.shape

(851264, 5)

In [0]:
shares.drop(shares.index[1000:], axis=0, inplace=True)


In [41]:
shares.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [42]:
shares.tail()

open      close        low       high      volume
995  63.310001  63.590000  63.240002  63.639999   2133200.0
996  27.160000  26.990000  26.680000  27.299999   1982400.0
997  28.320000  28.770000  28.010000  28.809999  37152800.0
998  44.000000  44.799999  43.750000  44.810001   6568600.0
999  36.080002  37.139999  36.009998  37.230000   5604300.0

In [43]:
shares.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = shares.drop("volume", axis=1)
y = shares["volume"]



In [45]:
X.shape

(1000, 4)

In [46]:
y.shape

(1000,)

In [0]:
# Normalize the label column by deviding the values by 1000000
y = y.div(1000000)

In [48]:
y.head(10)

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
5    1.0980
6    0.9496
7    0.7853
8    1.0937
9    1.5235
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
features = X.to_numpy()

In [0]:
labels = y.to_numpy()

In [54]:
features


array([[123.43    , 125.839996, 122.309998, 126.25    ],
       [125.239998, 119.980003, 119.940002, 125.540001],
       [116.379997, 114.949997, 114.93    , 119.739998],
       ...,
       [ 28.32    ,  28.77    ,  28.01    ,  28.809999],
       [ 44.      ,  44.799999,  43.75    ,  44.810001],
       [ 36.080002,  37.139999,  36.009998,  37.23    ]])

In [55]:
features.dtype

dtype('float64')

In [0]:
features = features.astype('float32')

In [57]:
features.dtype

dtype('float32')

In [58]:
labels.dtype

dtype('float64')

In [0]:
labels = labels.astype('float32')

In [60]:
labels.dtype

dtype('float32')

In [61]:
features

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       ...,
       [ 28.32,  28.77,  28.01,  28.81],
       [ 44.  ,  44.8 ,  43.75,  44.81],
       [ 36.08,  37.14,  36.01,  37.23]], dtype=float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
features = tf.math.l2_normalize(
    features,
    axis=None,
    epsilon=1e-12,
    name=None
)

In [63]:
features

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1)) 

In [65]:
W

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [66]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(x1, W, b):
    y_pred = tf.add(tf.matmul(x1, W), b)
    return y_pred

In [0]:
#print(prediction(features, W, b))

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
  diff = y_actual - y_predicted
  sqr = tf.square(diff)
  avg = tf.reduce_mean(sqr)
  return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
  # Record all the mathematical steps to calculate Loss on 'tape'
  with tf.GradientTape as t:
    t.watch([w,b]) 
    curr_prediction = prediction(x, w, b)
    current_loss = loss(y_actual, curr_prediction)
    dw, db = t.gradient(current_loss,[w, b])
    w = w - learning_rate * dw
    b = b - learning_rate * db
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [70]:
for i in range(100):
  W, b = train(features, labels, W, b)
  print("Current Training loss at Iteration", i, los(labels, prediction(features, W, b)).numpy())

AttributeError: ignored

### Observe values of Weight
- Print the updated values

### Observe values of Bias
- Print the updated values